/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RollCalculatorRouteImport } from './routes/roll-calculator'
import { Route as IndexRouteImport } from './routes/index'

const RollCalculatorRoute = RollCalculatorRouteImport.update({
  id: '/roll-calculator',
  path: '/roll-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/roll-calculator': typeof RollCalculatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/roll-calculator': typeof RollCalculatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/roll-calculator': typeof RollCalculatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/roll-calculator'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/roll-calculator'
  id: '__root__' | '/' | '/roll-calculator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RollCalculatorRoute: typeof RollCalculatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roll-calculator': {
      id: '/roll-calculator'
      path: '/roll-calculator'
      fullPath: '/roll-calculator'
      preLoaderRoute: typeof RollCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RollCalculatorRoute: RollCalculatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
